#!/usr/bin/env python3
"""Load the Ghana EML drug catalogue + demo inventory into Supabase Postgres.

One row per generic, brand-led display names. Idempotent: catalogue upserts on
ndc_code (GH-EML-XXXX, stable by file position); inventory upserts on
(pharmacy_id, drug_id).

Usage:
  python3 load_catalogue.py --dry-run        # validate + preview, no writes
  python3 load_catalogue.py --apply          # validate + write to local DB
  python3 load_catalogue.py --apply --no-inventory   # catalogue only

Requires the local Supabase stack (docker exec supabase_db_pharmacily psql).
"""
import argparse
import json
import subprocess
import sys
from pathlib import Path

HERE = Path(__file__).parent
REPO = HERE.parent
SEED_JSON = REPO / "pharmacily-web" / "src" / "data" / "drugs.seed.json"

ERNEST = "c945a0f5-7b1b-4749-891f-44465c5b7639"      # Ernest Chemists, Accra
DANADAMS = "cea459b3-2618-4634-b8a1-a519d137cf0f"    # Danadams Pharmacy, Kumasi

# (1-based catalogue index, pharmacy, qty, price_pesewas) — 25 demo rows.
# Overlaps on Coartem/Amoxicillin/Paracetamol/ORS/Lisinopril with different
# prices so comparison shows; a few low-stock rows light up Alerts.
DEMO_STOCK = [
    (1, "ernest", 320, 3850), (1, "danadams", 140, 3600),      # Coartem
    (19, "ernest", 240, 2400), (19, "danadams", 12, 2100),     # Amoxicillin
    (114, "ernest", 1120, 650), (114, "danadams", 400, 500),   # Paracetamol
    (103, "ernest", 500, 400), (103, "danadams", 60, 350),     # ORS
    (61, "ernest", 310, 1800), (61, "danadams", 45, 1500),     # Lisinopril
    (22, "ernest", 88, 4600),                                  # Augmentin
    (29, "ernest", 150, 2200),                                 # Ciprofloxacin
    (31, "danadams", 200, 1200),                               # Flagyl
    (32, "ernest", 64, 3500),                                  # Zithromax
    (59, "danadams", 90, 1600),                                # Amlodipine
    (71, "danadams", 6, 2800),                                 # Lipitor (low)
    (89, "ernest", 175, 1400),                                 # Metformin
    (96, "ernest", 210, 1800),                                 # Losec
    (104, "danadams", 95, 900),                                # Zinc
    (136, "ernest", 460, 1100),                                # Brufen
    (146, "ernest", 208, 900), (146, "danadams", 12, 750),     # Zyrtec (low @D)
    (153, "ernest", 8, 4200),                                  # Ventolin (low)
    (159, "danadams", 130, 1900),                              # Mucosolvan
    (165, "ernest", 75, 2400),                                 # Canesten
]
PHARMACY_IDS = {"ernest": ERNEST, "danadams": DANADAMS}

VALID_RX = {"Rx", "OTC"}
VALID_ATC1 = set("ABCDGHJLMNPRSV")  # mirrors AtcLevel1 in pharmacily-web/src/data/drugs.ts


def sql_str(v):
    if v is None:
        return "NULL"
    return "'" + str(v).replace("'", "''") + "'"


def sql_bool(v):
    return "TRUE" if v else "FALSE"


def validate(entry, i):
    errs = []
    for f in ("generic_name", "strength", "form", "atc_code", "atc_level1",
              "atc_group", "therapeutic_category", "shopper_category",
              "rx_otc", "ghana_eml", "nhis_covered"):
        if f not in entry or entry[f] in (None, ""):
            errs.append(f"row {i}: missing {f}")
    if entry.get("rx_otc") not in VALID_RX:
        errs.append(f"row {i}: bad rx_otc {entry.get('rx_otc')!r}")
    if entry.get("atc_level1") not in VALID_ATC1:
        errs.append(f"row {i}: bad atc_level1 {entry.get('atc_level1')!r}")
    if not entry.get("brand_examples_gh"):
        errs.append(f"row {i}: empty brand_examples_gh")
    if not entry.get("manufacturer_examples"):
        errs.append(f"row {i}: empty manufacturer_examples")
    return errs


def build_catalogue_sql(drugs):
    lines = ["-- Generated by supabase/load_catalogue.py — do not hand-edit.",
             "INSERT INTO drugs (name, generic_name, ndc_code, strength, form, manufacturer,",
             "  rx_otc, atc_code, therapeutic_category, shopper_category, nhis_covered, ghana_eml)",
             "VALUES"]
    rows = []
    for i, d in enumerate(drugs, start=1):
        code = f"GH-EML-{i:04d}"
        name = f"{d['brand_examples_gh'][0]} {d['strength']} {d['form']}"
        rows.append(
            f"({sql_str(name)}, {sql_str(d['generic_name'])}, '{code}', "
            f"{sql_str(d['strength'])}, {sql_str(d['form'])}, "
            f"{sql_str(d['manufacturer_examples'][0])}, "
            f"{sql_str(d['rx_otc'])}, {sql_str(d['atc_code'])}, "
            f"{sql_str(d['therapeutic_category'])}, {sql_str(d['shopper_category'])}, "
            f"{sql_bool(d['nhis_covered'])}, {sql_bool(d['ghana_eml'])})"
        )
    lines.append(",\n".join(rows))
    lines.append(
        "ON CONFLICT (ndc_code) DO UPDATE SET name = EXCLUDED.name,"
        " generic_name = EXCLUDED.generic_name, strength = EXCLUDED.strength,"
        " form = EXCLUDED.form, manufacturer = EXCLUDED.manufacturer,"
        " rx_otc = EXCLUDED.rx_otc, atc_code = EXCLUDED.atc_code,"
        " therapeutic_category = EXCLUDED.therapeutic_category,"
        " shopper_category = EXCLUDED.shopper_category,"
        " nhis_covered = EXCLUDED.nhis_covered, ghana_eml = EXCLUDED.ghana_eml;"
    )
    return "\n".join(lines), {f"GH-EML-{i:04d}": d for i, d in enumerate(drugs, start=1)}


def build_inventory_sql(by_code):
    lines = ["-- Generated demo inventory — idempotent on (pharmacy_id, drug_id).",
             "INSERT INTO inventory (pharmacy_id, drug_id, quantity, price_cents, source)",
             "VALUES"]
    rows = []
    plan = []
    for idx, which, qty, price in DEMO_STOCK:
        code = f"GH-EML-{idx:04d}"
        d = by_code[code]
        name = f"{d['brand_examples_gh'][0]} {d['strength']} {d['form']}"
        rows.append(
            f"('{PHARMACY_IDS[which]}', (SELECT id FROM drugs WHERE ndc_code = '{code}'), "
            f"{qty}, {price}, 'manual')"
        )
        plan.append(f"  {which:8s} {name} — {qty} left, Gh₵ {price/100:.2f}")
    lines.append(",\n".join(rows))
    lines.append(
        "ON CONFLICT (pharmacy_id, drug_id) DO UPDATE SET quantity = EXCLUDED.quantity,"
        " price_cents = EXCLUDED.price_cents, last_updated = now(), source = EXCLUDED.source;"
    )
    return "\n".join(lines), plan


def psql(sql):
    p = subprocess.run(
        ["docker", "exec", "-i", "supabase_db_pharmacily",
         "psql", "-U", "postgres", "-v", "ON_ERROR_STOP=1"],
        input=sql.encode(), capture_output=True, cwd=REPO,
    )
    return p.returncode, p.stdout.decode()[-500:], p.stderr.decode()[-500:]


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--dry-run", action="store_true")
    ap.add_argument("--apply", action="store_true")
    ap.add_argument("--no-inventory", action="store_true")
    args = ap.parse_args()
    if not args.dry_run and not args.apply:
        ap.error("pass --dry-run or --apply")

    seed = json.loads(SEED_JSON.read_text())
    drugs = seed["drugs"]
    errs = [e for i, d in enumerate(drugs, 1) for e in validate(d, i)]
    if errs:
        print(f"VALIDATION FAILED ({len(errs)}):")
        print("\n".join(errs[:15]))
        sys.exit(1)
    print(f"validated {len(drugs)} entries OK "
          f"({sum(d['rx_otc']=='Rx' for d in drugs)} Rx / "
          f"{sum(d['rx_otc']=='OTC' for d in drugs)} OTC)")

    cat_sql, by_code = build_catalogue_sql(drugs)
    print(f"catalogue SQL: {len(drugs)} rows, e.g. "
          f"{by_code['GH-EML-0001']['brand_examples_gh'][0]} / "
          f"{by_code['GH-EML-0114']['brand_examples_gh'][0]}")

    inv_sql, plan = ("", []) if args.no_inventory else build_inventory_sql(by_code)
    if plan:
        print(f"inventory plan ({len(plan)} rows):")
        print("\n".join(plan))

    if args.dry_run:
        print("dry run — nothing written.")
        return

    rc, out, err = psql(cat_sql)
    if rc != 0:
        print("CATALOGUE APPLY FAILED:", out, err)
        sys.exit(1)
    print("catalogue applied.")
    if inv_sql:
        rc, out, err = psql(inv_sql)
        if rc != 0:
            print("INVENTORY APPLY FAILED:", out, err)
            sys.exit(1)
        print("inventory applied.")


if __name__ == "__main__":
    main()
