// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"database/sql/driver"
	"fmt"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type InventorySource string

const (
	InventorySourceApi     InventorySource = "api"
	InventorySourceManual  InventorySource = "manual"
	InventorySourceWebhook InventorySource = "webhook"
	InventorySourceCsv     InventorySource = "csv"
)

func (e *InventorySource) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = InventorySource(s)
	case string:
		*e = InventorySource(s)
	default:
		return fmt.Errorf("unsupported scan type for InventorySource: %T", src)
	}
	return nil
}

type NullInventorySource struct {
	InventorySource InventorySource `json:"inventory_source"`
	Valid           bool            `json:"valid"` // Valid is true if InventorySource is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullInventorySource) Scan(value interface{}) error {
	if value == nil {
		ns.InventorySource, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.InventorySource.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullInventorySource) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.InventorySource), nil
}

type SyncStatus string

const (
	SyncStatusSuccess SyncStatus = "success"
	SyncStatusPartial SyncStatus = "partial"
	SyncStatusFailed  SyncStatus = "failed"
	SyncStatusPending SyncStatus = "pending"
)

func (e *SyncStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = SyncStatus(s)
	case string:
		*e = SyncStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for SyncStatus: %T", src)
	}
	return nil
}

type NullSyncStatus struct {
	SyncStatus SyncStatus `json:"sync_status"`
	Valid      bool       `json:"valid"` // Valid is true if SyncStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullSyncStatus) Scan(value interface{}) error {
	if value == nil {
		ns.SyncStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.SyncStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullSyncStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.SyncStatus), nil
}

type Drug struct {
	ID                  uuid.UUID          `json:"id"`
	Name                string             `json:"name"`
	GenericName         string             `json:"generic_name"`
	NdcCode             string             `json:"ndc_code"`
	Strength            pgtype.Text        `json:"strength"`
	Form                pgtype.Text        `json:"form"`
	Manufacturer        pgtype.Text        `json:"manufacturer"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	RxOtc               pgtype.Text        `json:"rx_otc"`
	AtcCode             pgtype.Text        `json:"atc_code"`
	TherapeuticCategory pgtype.Text        `json:"therapeutic_category"`
	ShopperCategory     pgtype.Text        `json:"shopper_category"`
	NhisCovered         pgtype.Bool        `json:"nhis_covered"`
	GhanaEml            pgtype.Bool        `json:"ghana_eml"`
}

type GeocodeCache struct {
	AddressHash string             `json:"address_hash"`
	Address     string             `json:"address"`
	Latitude    float64            `json:"latitude"`
	Longitude   float64            `json:"longitude"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type Inventory struct {
	ID          uuid.UUID       `json:"id"`
	PharmacyID  uuid.UUID       `json:"pharmacy_id"`
	DrugID      uuid.UUID       `json:"drug_id"`
	Quantity    int32           `json:"quantity"`
	PriceCents  pgtype.Int4     `json:"price_cents"`
	LastUpdated time.Time       `json:"last_updated"`
	Source      InventorySource `json:"source"`
}

type Pharmacy struct {
	ID                      uuid.UUID          `json:"id"`
	Name                    string             `json:"name"`
	Address                 string             `json:"address"`
	City                    string             `json:"city"`
	State                   string             `json:"state"`
	ZipCode                 string             `json:"zip_code"`
	Latitude                float64            `json:"latitude"`
	Longitude               float64            `json:"longitude"`
	Phone                   pgtype.Text        `json:"phone"`
	Hours                   []byte             `json:"hours"`
	ChainID                 pgtype.UUID        `json:"chain_id"`
	ApiCredentialsEncrypted pgtype.Text        `json:"api_credentials_encrypted"`
	IsActive                pgtype.Bool        `json:"is_active"`
	CreatedAt               pgtype.Timestamptz `json:"created_at"`
	UpdatedAt               pgtype.Timestamptz `json:"updated_at"`
}

type PharmacyApiConfig struct {
	ID             uuid.UUID          `json:"id"`
	PharmacyID     uuid.UUID          `json:"pharmacy_id"`
	ApiType        string             `json:"api_type"`
	Endpoint       pgtype.Text        `json:"endpoint"`
	CredentialsRef pgtype.Text        `json:"credentials_ref"`
	SyncSchedule   pgtype.Text        `json:"sync_schedule"`
	LastSyncAt     pgtype.Timestamptz `json:"last_sync_at"`
	LastSyncStatus NullSyncStatus     `json:"last_sync_status"`
	IsEnabled      pgtype.Bool        `json:"is_enabled"`
}

type PharmacyChain struct {
	ID           uuid.UUID          `json:"id"`
	Name         string             `json:"name"`
	ApiType      string             `json:"api_type"`
	BaseEndpoint pgtype.Text        `json:"base_endpoint"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type StockTakeLine struct {
	ID         uuid.UUID   `json:"id"`
	SessionID  uuid.UUID   `json:"session_id"`
	DrugID     uuid.UUID   `json:"drug_id"`
	SystemQty  int32       `json:"system_qty"`
	CountedQty pgtype.Int4 `json:"counted_qty"`
	Note       pgtype.Text `json:"note"`
}

type StockTakeSession struct {
	ID          uuid.UUID          `json:"id"`
	PharmacyID  uuid.UUID          `json:"pharmacy_id"`
	Status      string             `json:"status"`
	Notes       pgtype.Text        `json:"notes"`
	CreatedBy   pgtype.UUID        `json:"created_by"`
	DecidedBy   pgtype.UUID        `json:"decided_by"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	SubmittedAt pgtype.Timestamptz `json:"submitted_at"`
	DecidedAt   pgtype.Timestamptz `json:"decided_at"`
}

type SyncRetryQueue struct {
	ID            uuid.UUID          `json:"id"`
	PharmacyID    uuid.UUID          `json:"pharmacy_id"`
	DrugID        pgtype.UUID        `json:"drug_id"`
	AttemptCount  pgtype.Int4        `json:"attempt_count"`
	LastAttemptAt pgtype.Timestamptz `json:"last_attempt_at"`
	NextRetryAt   time.Time          `json:"next_retry_at"`
	ErrorMessage  pgtype.Text        `json:"error_message"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type UserFavorite struct {
	ID            uuid.UUID          `json:"id"`
	UserID        uuid.UUID          `json:"user_id"`
	DrugID        uuid.UUID          `json:"drug_id"`
	PharmacyID    pgtype.UUID        `json:"pharmacy_id"`
	NotifyOnStock pgtype.Bool        `json:"notify_on_stock"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}
