// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: pharmacy.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const addToRetryQueue = `-- name: AddToRetryQueue :one
INSERT INTO sync_retry_queue (pharmacy_id, drug_id, attempt_count, last_attempt_at, next_retry_at, error_message)
VALUES ($1, $2, $3, now(), $4, $5)
RETURNING id, pharmacy_id, drug_id, attempt_count, last_attempt_at, next_retry_at, error_message, created_at
`

type AddToRetryQueueParams struct {
	PharmacyID   uuid.UUID   `json:"pharmacy_id"`
	DrugID       pgtype.UUID `json:"drug_id"`
	AttemptCount pgtype.Int4 `json:"attempt_count"`
	NextRetryAt  time.Time   `json:"next_retry_at"`
	ErrorMessage pgtype.Text `json:"error_message"`
}

func (q *Queries) AddToRetryQueue(ctx context.Context, arg AddToRetryQueueParams) (SyncRetryQueue, error) {
	row := q.db.QueryRow(ctx, addToRetryQueue,
		arg.PharmacyID,
		arg.DrugID,
		arg.AttemptCount,
		arg.NextRetryAt,
		arg.ErrorMessage,
	)
	var i SyncRetryQueue
	err := row.Scan(
		&i.ID,
		&i.PharmacyID,
		&i.DrugID,
		&i.AttemptCount,
		&i.LastAttemptAt,
		&i.NextRetryAt,
		&i.ErrorMessage,
		&i.CreatedAt,
	)
	return i, err
}

const bulkUpsertInventory = `-- name: BulkUpsertInventory :exec
INSERT INTO inventory (pharmacy_id, drug_id, quantity, price_cents, last_updated, source)
VALUES ($1, $2, $3, $4, now(), $5)
ON CONFLICT (pharmacy_id, drug_id) DO UPDATE SET
    quantity = EXCLUDED.quantity,
    price_cents = EXCLUDED.price_cents,
    last_updated = now(),
    source = EXCLUDED.source
`

type BulkUpsertInventoryParams struct {
	PharmacyID uuid.UUID       `json:"pharmacy_id"`
	DrugID     uuid.UUID       `json:"drug_id"`
	Quantity   int32           `json:"quantity"`
	PriceCents pgtype.Int4     `json:"price_cents"`
	Source     InventorySource `json:"source"`
}

func (q *Queries) BulkUpsertInventory(ctx context.Context, arg BulkUpsertInventoryParams) error {
	_, err := q.db.Exec(ctx, bulkUpsertInventory,
		arg.PharmacyID,
		arg.DrugID,
		arg.Quantity,
		arg.PriceCents,
		arg.Source,
	)
	return err
}

const createDrug = `-- name: CreateDrug :one
INSERT INTO drugs (name, generic_name, ndc_code, strength, form, manufacturer)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, name, generic_name, ndc_code, strength, form, manufacturer, created_at, rx_otc, atc_code, therapeutic_category, shopper_category, nhis_covered, ghana_eml
`

type CreateDrugParams struct {
	Name         string      `json:"name"`
	GenericName  string      `json:"generic_name"`
	NdcCode      string      `json:"ndc_code"`
	Strength     pgtype.Text `json:"strength"`
	Form         pgtype.Text `json:"form"`
	Manufacturer pgtype.Text `json:"manufacturer"`
}

func (q *Queries) CreateDrug(ctx context.Context, arg CreateDrugParams) (Drug, error) {
	row := q.db.QueryRow(ctx, createDrug,
		arg.Name,
		arg.GenericName,
		arg.NdcCode,
		arg.Strength,
		arg.Form,
		arg.Manufacturer,
	)
	var i Drug
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.GenericName,
		&i.NdcCode,
		&i.Strength,
		&i.Form,
		&i.Manufacturer,
		&i.CreatedAt,
		&i.RxOtc,
		&i.AtcCode,
		&i.TherapeuticCategory,
		&i.ShopperCategory,
		&i.NhisCovered,
		&i.GhanaEml,
	)
	return i, err
}

const createPharmacy = `-- name: CreatePharmacy :one
INSERT INTO pharmacies (name, address, city, state, zip_code, latitude, longitude, phone, hours, chain_id, api_credentials_encrypted)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
RETURNING id, name, address, city, state, zip_code, latitude, longitude, phone, hours, chain_id, api_credentials_encrypted, is_active, created_at, updated_at
`

type CreatePharmacyParams struct {
	Name                    string      `json:"name"`
	Address                 string      `json:"address"`
	City                    string      `json:"city"`
	State                   string      `json:"state"`
	ZipCode                 string      `json:"zip_code"`
	Latitude                float64     `json:"latitude"`
	Longitude               float64     `json:"longitude"`
	Phone                   pgtype.Text `json:"phone"`
	Hours                   []byte      `json:"hours"`
	ChainID                 pgtype.UUID `json:"chain_id"`
	ApiCredentialsEncrypted pgtype.Text `json:"api_credentials_encrypted"`
}

func (q *Queries) CreatePharmacy(ctx context.Context, arg CreatePharmacyParams) (Pharmacy, error) {
	row := q.db.QueryRow(ctx, createPharmacy,
		arg.Name,
		arg.Address,
		arg.City,
		arg.State,
		arg.ZipCode,
		arg.Latitude,
		arg.Longitude,
		arg.Phone,
		arg.Hours,
		arg.ChainID,
		arg.ApiCredentialsEncrypted,
	)
	var i Pharmacy
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Address,
		&i.City,
		&i.State,
		&i.ZipCode,
		&i.Latitude,
		&i.Longitude,
		&i.Phone,
		&i.Hours,
		&i.ChainID,
		&i.ApiCredentialsEncrypted,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createPharmacyChain = `-- name: CreatePharmacyChain :one
INSERT INTO pharmacy_chains (name, api_type, base_endpoint)
VALUES ($1, $2, $3)
RETURNING id, name, api_type, base_endpoint, created_at
`

type CreatePharmacyChainParams struct {
	Name         string      `json:"name"`
	ApiType      string      `json:"api_type"`
	BaseEndpoint pgtype.Text `json:"base_endpoint"`
}

func (q *Queries) CreatePharmacyChain(ctx context.Context, arg CreatePharmacyChainParams) (PharmacyChain, error) {
	row := q.db.QueryRow(ctx, createPharmacyChain, arg.Name, arg.ApiType, arg.BaseEndpoint)
	var i PharmacyChain
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ApiType,
		&i.BaseEndpoint,
		&i.CreatedAt,
	)
	return i, err
}

const createUserFavorite = `-- name: CreateUserFavorite :one
INSERT INTO user_favorites (user_id, drug_id, pharmacy_id, notify_on_stock)
VALUES ($1, $2, $3, $4)
ON CONFLICT (user_id, drug_id, pharmacy_id) DO UPDATE SET
    notify_on_stock = EXCLUDED.notify_on_stock
RETURNING id, user_id, drug_id, pharmacy_id, notify_on_stock, created_at
`

type CreateUserFavoriteParams struct {
	UserID        uuid.UUID   `json:"user_id"`
	DrugID        uuid.UUID   `json:"drug_id"`
	PharmacyID    pgtype.UUID `json:"pharmacy_id"`
	NotifyOnStock pgtype.Bool `json:"notify_on_stock"`
}

func (q *Queries) CreateUserFavorite(ctx context.Context, arg CreateUserFavoriteParams) (UserFavorite, error) {
	row := q.db.QueryRow(ctx, createUserFavorite,
		arg.UserID,
		arg.DrugID,
		arg.PharmacyID,
		arg.NotifyOnStock,
	)
	var i UserFavorite
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DrugID,
		&i.PharmacyID,
		&i.NotifyOnStock,
		&i.CreatedAt,
	)
	return i, err
}

const deleteDrug = `-- name: DeleteDrug :exec
DELETE FROM drugs WHERE id = $1
`

func (q *Queries) DeleteDrug(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteDrug, id)
	return err
}

const deletePharmacy = `-- name: DeletePharmacy :exec
DELETE FROM pharmacies WHERE id = $1
`

func (q *Queries) DeletePharmacy(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deletePharmacy, id)
	return err
}

const deletePharmacyChain = `-- name: DeletePharmacyChain :exec
DELETE FROM pharmacy_chains WHERE id = $1
`

func (q *Queries) DeletePharmacyChain(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deletePharmacyChain, id)
	return err
}

const deleteRetryQueueItem = `-- name: DeleteRetryQueueItem :exec
DELETE FROM sync_retry_queue WHERE id = $1
`

func (q *Queries) DeleteRetryQueueItem(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteRetryQueueItem, id)
	return err
}

const deleteUserFavorite = `-- name: DeleteUserFavorite :exec
DELETE FROM user_favorites WHERE user_id = $1 AND drug_id = $2 AND pharmacy_id = $3
`

type DeleteUserFavoriteParams struct {
	UserID     uuid.UUID   `json:"user_id"`
	DrugID     uuid.UUID   `json:"drug_id"`
	PharmacyID pgtype.UUID `json:"pharmacy_id"`
}

func (q *Queries) DeleteUserFavorite(ctx context.Context, arg DeleteUserFavoriteParams) error {
	_, err := q.db.Exec(ctx, deleteUserFavorite, arg.UserID, arg.DrugID, arg.PharmacyID)
	return err
}

const getDrugByID = `-- name: GetDrugByID :one
SELECT id, name, generic_name, ndc_code, strength, form, manufacturer, created_at, rx_otc, atc_code, therapeutic_category, shopper_category, nhis_covered, ghana_eml FROM drugs WHERE id = $1
`

func (q *Queries) GetDrugByID(ctx context.Context, id uuid.UUID) (Drug, error) {
	row := q.db.QueryRow(ctx, getDrugByID, id)
	var i Drug
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.GenericName,
		&i.NdcCode,
		&i.Strength,
		&i.Form,
		&i.Manufacturer,
		&i.CreatedAt,
		&i.RxOtc,
		&i.AtcCode,
		&i.TherapeuticCategory,
		&i.ShopperCategory,
		&i.NhisCovered,
		&i.GhanaEml,
	)
	return i, err
}

const getDrugByNDC = `-- name: GetDrugByNDC :one
SELECT id, name, generic_name, ndc_code, strength, form, manufacturer, created_at, rx_otc, atc_code, therapeutic_category, shopper_category, nhis_covered, ghana_eml FROM drugs WHERE ndc_code = $1
`

func (q *Queries) GetDrugByNDC(ctx context.Context, ndcCode string) (Drug, error) {
	row := q.db.QueryRow(ctx, getDrugByNDC, ndcCode)
	var i Drug
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.GenericName,
		&i.NdcCode,
		&i.Strength,
		&i.Form,
		&i.Manufacturer,
		&i.CreatedAt,
		&i.RxOtc,
		&i.AtcCode,
		&i.TherapeuticCategory,
		&i.ShopperCategory,
		&i.NhisCovered,
		&i.GhanaEml,
	)
	return i, err
}

const getDueRetryQueue = `-- name: GetDueRetryQueue :many
SELECT id, pharmacy_id, drug_id, attempt_count, last_attempt_at, next_retry_at, error_message, created_at FROM sync_retry_queue
WHERE next_retry_at <= now()
ORDER BY next_retry_at
LIMIT $1
`

func (q *Queries) GetDueRetryQueue(ctx context.Context, limit int32) ([]SyncRetryQueue, error) {
	rows, err := q.db.Query(ctx, getDueRetryQueue, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SyncRetryQueue
	for rows.Next() {
		var i SyncRetryQueue
		if err := rows.Scan(
			&i.ID,
			&i.PharmacyID,
			&i.DrugID,
			&i.AttemptCount,
			&i.LastAttemptAt,
			&i.NextRetryAt,
			&i.ErrorMessage,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEnabledPharmacyAPIConfigs = `-- name: GetEnabledPharmacyAPIConfigs :many
SELECT pac.id, pac.pharmacy_id, pac.api_type, pac.endpoint, pac.credentials_ref, pac.sync_schedule, pac.last_sync_at, pac.last_sync_status, pac.is_enabled, p.name as pharmacy_name, p.latitude, p.longitude
FROM pharmacy_api_configs pac
JOIN pharmacies p ON pac.pharmacy_id = p.id
WHERE pac.is_enabled = true
`

type GetEnabledPharmacyAPIConfigsRow struct {
	ID             uuid.UUID          `json:"id"`
	PharmacyID     uuid.UUID          `json:"pharmacy_id"`
	ApiType        string             `json:"api_type"`
	Endpoint       pgtype.Text        `json:"endpoint"`
	CredentialsRef pgtype.Text        `json:"credentials_ref"`
	SyncSchedule   pgtype.Text        `json:"sync_schedule"`
	LastSyncAt     pgtype.Timestamptz `json:"last_sync_at"`
	LastSyncStatus NullSyncStatus     `json:"last_sync_status"`
	IsEnabled      pgtype.Bool        `json:"is_enabled"`
	PharmacyName   string             `json:"pharmacy_name"`
	Latitude       float64            `json:"latitude"`
	Longitude      float64            `json:"longitude"`
}

func (q *Queries) GetEnabledPharmacyAPIConfigs(ctx context.Context) ([]GetEnabledPharmacyAPIConfigsRow, error) {
	rows, err := q.db.Query(ctx, getEnabledPharmacyAPIConfigs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetEnabledPharmacyAPIConfigsRow
	for rows.Next() {
		var i GetEnabledPharmacyAPIConfigsRow
		if err := rows.Scan(
			&i.ID,
			&i.PharmacyID,
			&i.ApiType,
			&i.Endpoint,
			&i.CredentialsRef,
			&i.SyncSchedule,
			&i.LastSyncAt,
			&i.LastSyncStatus,
			&i.IsEnabled,
			&i.PharmacyName,
			&i.Latitude,
			&i.Longitude,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getGeocodeCache = `-- name: GetGeocodeCache :one
SELECT address_hash, address, latitude, longitude, created_at FROM geocode_cache WHERE address_hash = $1
`

func (q *Queries) GetGeocodeCache(ctx context.Context, addressHash string) (GeocodeCache, error) {
	row := q.db.QueryRow(ctx, getGeocodeCache, addressHash)
	var i GeocodeCache
	err := row.Scan(
		&i.AddressHash,
		&i.Address,
		&i.Latitude,
		&i.Longitude,
		&i.CreatedAt,
	)
	return i, err
}

const getInventoryByPharmacyAndDrug = `-- name: GetInventoryByPharmacyAndDrug :one
SELECT i.id, i.pharmacy_id, i.drug_id, i.quantity, i.price_cents, i.last_updated, i.source, d.name as drug_name, d.generic_name, d.ndc_code, d.strength, d.form
FROM inventory i
JOIN drugs d ON i.drug_id = d.id
WHERE i.pharmacy_id = $1 AND i.drug_id = $2
`

type GetInventoryByPharmacyAndDrugParams struct {
	PharmacyID uuid.UUID `json:"pharmacy_id"`
	DrugID     uuid.UUID `json:"drug_id"`
}

type GetInventoryByPharmacyAndDrugRow struct {
	ID          uuid.UUID       `json:"id"`
	PharmacyID  uuid.UUID       `json:"pharmacy_id"`
	DrugID      uuid.UUID       `json:"drug_id"`
	Quantity    int32           `json:"quantity"`
	PriceCents  pgtype.Int4     `json:"price_cents"`
	LastUpdated time.Time       `json:"last_updated"`
	Source      InventorySource `json:"source"`
	DrugName    string          `json:"drug_name"`
	GenericName string          `json:"generic_name"`
	NdcCode     string          `json:"ndc_code"`
	Strength    pgtype.Text     `json:"strength"`
	Form        pgtype.Text     `json:"form"`
}

func (q *Queries) GetInventoryByPharmacyAndDrug(ctx context.Context, arg GetInventoryByPharmacyAndDrugParams) (GetInventoryByPharmacyAndDrugRow, error) {
	row := q.db.QueryRow(ctx, getInventoryByPharmacyAndDrug, arg.PharmacyID, arg.DrugID)
	var i GetInventoryByPharmacyAndDrugRow
	err := row.Scan(
		&i.ID,
		&i.PharmacyID,
		&i.DrugID,
		&i.Quantity,
		&i.PriceCents,
		&i.LastUpdated,
		&i.Source,
		&i.DrugName,
		&i.GenericName,
		&i.NdcCode,
		&i.Strength,
		&i.Form,
	)
	return i, err
}

const getPharmaciesNearby = `-- name: GetPharmaciesNearby :many
SELECT
    p.id, p.name, p.address, p.city, p.state, p.zip_code, p.latitude, p.longitude, p.phone, p.hours, p.chain_id, p.api_credentials_encrypted, p.is_active, p.created_at, p.updated_at,
    pc.name as chain_name,
    pc.api_type as chain_api_type,
    earth_distance(ll_to_earth($1, $2), ll_to_earth(p.latitude, p.longitude)) as distance_meters
FROM pharmacies p
LEFT JOIN pharmacy_chains pc ON p.chain_id = pc.id
WHERE p.is_active = true
  AND earth_box(ll_to_earth($1, $2), $3) @> ll_to_earth(p.latitude, p.longitude)
ORDER BY distance_meters
LIMIT $4
`

type GetPharmaciesNearbyParams struct {
	LlToEarth   float64 `json:"ll_to_earth"`
	LlToEarth_2 float64 `json:"ll_to_earth_2"`
	EarthBox    float64 `json:"earth_box"`
	Limit       int32   `json:"limit"`
}

type GetPharmaciesNearbyRow struct {
	ID                      uuid.UUID          `json:"id"`
	Name                    string             `json:"name"`
	Address                 string             `json:"address"`
	City                    string             `json:"city"`
	State                   string             `json:"state"`
	ZipCode                 string             `json:"zip_code"`
	Latitude                float64            `json:"latitude"`
	Longitude               float64            `json:"longitude"`
	Phone                   pgtype.Text        `json:"phone"`
	Hours                   []byte             `json:"hours"`
	ChainID                 pgtype.UUID        `json:"chain_id"`
	ApiCredentialsEncrypted pgtype.Text        `json:"api_credentials_encrypted"`
	IsActive                pgtype.Bool        `json:"is_active"`
	CreatedAt               pgtype.Timestamptz `json:"created_at"`
	UpdatedAt               pgtype.Timestamptz `json:"updated_at"`
	ChainName               pgtype.Text        `json:"chain_name"`
	ChainApiType            pgtype.Text        `json:"chain_api_type"`
	DistanceMeters          float64            `json:"distance_meters"`
}

func (q *Queries) GetPharmaciesNearby(ctx context.Context, arg GetPharmaciesNearbyParams) ([]GetPharmaciesNearbyRow, error) {
	rows, err := q.db.Query(ctx, getPharmaciesNearby,
		arg.LlToEarth,
		arg.LlToEarth_2,
		arg.EarthBox,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPharmaciesNearbyRow
	for rows.Next() {
		var i GetPharmaciesNearbyRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Address,
			&i.City,
			&i.State,
			&i.ZipCode,
			&i.Latitude,
			&i.Longitude,
			&i.Phone,
			&i.Hours,
			&i.ChainID,
			&i.ApiCredentialsEncrypted,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ChainName,
			&i.ChainApiType,
			&i.DistanceMeters,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPharmacyAPIConfig = `-- name: GetPharmacyAPIConfig :one
SELECT id, pharmacy_id, api_type, endpoint, credentials_ref, sync_schedule, last_sync_at, last_sync_status, is_enabled FROM pharmacy_api_configs WHERE pharmacy_id = $1
`

func (q *Queries) GetPharmacyAPIConfig(ctx context.Context, pharmacyID uuid.UUID) (PharmacyApiConfig, error) {
	row := q.db.QueryRow(ctx, getPharmacyAPIConfig, pharmacyID)
	var i PharmacyApiConfig
	err := row.Scan(
		&i.ID,
		&i.PharmacyID,
		&i.ApiType,
		&i.Endpoint,
		&i.CredentialsRef,
		&i.SyncSchedule,
		&i.LastSyncAt,
		&i.LastSyncStatus,
		&i.IsEnabled,
	)
	return i, err
}

const getPharmacyByID = `-- name: GetPharmacyByID :one
SELECT
    p.id, p.name, p.address, p.city, p.state, p.zip_code, p.latitude, p.longitude, p.phone, p.hours, p.chain_id, p.api_credentials_encrypted, p.is_active, p.created_at, p.updated_at,
    pc.name as chain_name,
    pc.api_type as chain_api_type
FROM pharmacies p
LEFT JOIN pharmacy_chains pc ON p.chain_id = pc.id
WHERE p.id = $1
`

type GetPharmacyByIDRow struct {
	ID                      uuid.UUID          `json:"id"`
	Name                    string             `json:"name"`
	Address                 string             `json:"address"`
	City                    string             `json:"city"`
	State                   string             `json:"state"`
	ZipCode                 string             `json:"zip_code"`
	Latitude                float64            `json:"latitude"`
	Longitude               float64            `json:"longitude"`
	Phone                   pgtype.Text        `json:"phone"`
	Hours                   []byte             `json:"hours"`
	ChainID                 pgtype.UUID        `json:"chain_id"`
	ApiCredentialsEncrypted pgtype.Text        `json:"api_credentials_encrypted"`
	IsActive                pgtype.Bool        `json:"is_active"`
	CreatedAt               pgtype.Timestamptz `json:"created_at"`
	UpdatedAt               pgtype.Timestamptz `json:"updated_at"`
	ChainName               pgtype.Text        `json:"chain_name"`
	ChainApiType            pgtype.Text        `json:"chain_api_type"`
}

func (q *Queries) GetPharmacyByID(ctx context.Context, id uuid.UUID) (GetPharmacyByIDRow, error) {
	row := q.db.QueryRow(ctx, getPharmacyByID, id)
	var i GetPharmacyByIDRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Address,
		&i.City,
		&i.State,
		&i.ZipCode,
		&i.Latitude,
		&i.Longitude,
		&i.Phone,
		&i.Hours,
		&i.ChainID,
		&i.ApiCredentialsEncrypted,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ChainName,
		&i.ChainApiType,
	)
	return i, err
}

const getPharmacyChainByID = `-- name: GetPharmacyChainByID :one
SELECT id, name, api_type, base_endpoint, created_at FROM pharmacy_chains WHERE id = $1
`

func (q *Queries) GetPharmacyChainByID(ctx context.Context, id uuid.UUID) (PharmacyChain, error) {
	row := q.db.QueryRow(ctx, getPharmacyChainByID, id)
	var i PharmacyChain
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ApiType,
		&i.BaseEndpoint,
		&i.CreatedAt,
	)
	return i, err
}

const getPharmacyChains = `-- name: GetPharmacyChains :many
SELECT id, name, api_type, base_endpoint, created_at FROM pharmacy_chains ORDER BY name
`

func (q *Queries) GetPharmacyChains(ctx context.Context) ([]PharmacyChain, error) {
	rows, err := q.db.Query(ctx, getPharmacyChains)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PharmacyChain
	for rows.Next() {
		var i PharmacyChain
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.ApiType,
			&i.BaseEndpoint,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPharmacyInventory = `-- name: GetPharmacyInventory :many
SELECT i.id, i.pharmacy_id, i.drug_id, i.quantity, i.price_cents, i.last_updated, i.source, d.name as drug_name, d.generic_name, d.ndc_code, d.strength, d.form
FROM inventory i
JOIN drugs d ON i.drug_id = d.id
WHERE i.pharmacy_id = $1
ORDER BY d.name
LIMIT $2 OFFSET $3
`

type GetPharmacyInventoryParams struct {
	PharmacyID uuid.UUID `json:"pharmacy_id"`
	Limit      int32     `json:"limit"`
	Offset     int32     `json:"offset"`
}

type GetPharmacyInventoryRow struct {
	ID          uuid.UUID       `json:"id"`
	PharmacyID  uuid.UUID       `json:"pharmacy_id"`
	DrugID      uuid.UUID       `json:"drug_id"`
	Quantity    int32           `json:"quantity"`
	PriceCents  pgtype.Int4     `json:"price_cents"`
	LastUpdated time.Time       `json:"last_updated"`
	Source      InventorySource `json:"source"`
	DrugName    string          `json:"drug_name"`
	GenericName string          `json:"generic_name"`
	NdcCode     string          `json:"ndc_code"`
	Strength    pgtype.Text     `json:"strength"`
	Form        pgtype.Text     `json:"form"`
}

func (q *Queries) GetPharmacyInventory(ctx context.Context, arg GetPharmacyInventoryParams) ([]GetPharmacyInventoryRow, error) {
	rows, err := q.db.Query(ctx, getPharmacyInventory, arg.PharmacyID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPharmacyInventoryRow
	for rows.Next() {
		var i GetPharmacyInventoryRow
		if err := rows.Scan(
			&i.ID,
			&i.PharmacyID,
			&i.DrugID,
			&i.Quantity,
			&i.PriceCents,
			&i.LastUpdated,
			&i.Source,
			&i.DrugName,
			&i.GenericName,
			&i.NdcCode,
			&i.Strength,
			&i.Form,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserFavorites = `-- name: GetUserFavorites :many
SELECT
    uf.id, uf.user_id, uf.drug_id, uf.pharmacy_id, uf.notify_on_stock, uf.created_at,
    d.name as drug_name,
    d.generic_name,
    d.ndc_code,
    d.strength,
    d.form,
    p.name as pharmacy_name,
    p.address,
    p.city,
    p.state,
    p.latitude,
    p.longitude
FROM user_favorites uf
JOIN drugs d ON uf.drug_id = d.id
LEFT JOIN pharmacies p ON uf.pharmacy_id = p.id
WHERE uf.user_id = $1
ORDER BY uf.created_at DESC
`

type GetUserFavoritesRow struct {
	ID            uuid.UUID          `json:"id"`
	UserID        uuid.UUID          `json:"user_id"`
	DrugID        uuid.UUID          `json:"drug_id"`
	PharmacyID    pgtype.UUID        `json:"pharmacy_id"`
	NotifyOnStock pgtype.Bool        `json:"notify_on_stock"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	DrugName      string             `json:"drug_name"`
	GenericName   string             `json:"generic_name"`
	NdcCode       string             `json:"ndc_code"`
	Strength      pgtype.Text        `json:"strength"`
	Form          pgtype.Text        `json:"form"`
	PharmacyName  pgtype.Text        `json:"pharmacy_name"`
	Address       pgtype.Text        `json:"address"`
	City          pgtype.Text        `json:"city"`
	State         pgtype.Text        `json:"state"`
	Latitude      pgtype.Float8      `json:"latitude"`
	Longitude     pgtype.Float8      `json:"longitude"`
}

func (q *Queries) GetUserFavorites(ctx context.Context, userID uuid.UUID) ([]GetUserFavoritesRow, error) {
	rows, err := q.db.Query(ctx, getUserFavorites, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUserFavoritesRow
	for rows.Next() {
		var i GetUserFavoritesRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.DrugID,
			&i.PharmacyID,
			&i.NotifyOnStock,
			&i.CreatedAt,
			&i.DrugName,
			&i.GenericName,
			&i.NdcCode,
			&i.Strength,
			&i.Form,
			&i.PharmacyName,
			&i.Address,
			&i.City,
			&i.State,
			&i.Latitude,
			&i.Longitude,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchDrugs = `-- name: SearchDrugs :many
SELECT id, name, generic_name, ndc_code, strength, form, manufacturer, created_at, rx_otc, atc_code, therapeutic_category, shopper_category, nhis_covered, ghana_eml FROM drugs
WHERE name ILIKE $1 || '%' OR generic_name ILIKE $1 || '%'
   OR name % $1 OR generic_name % $1
ORDER BY (name ILIKE $1 || '%' OR generic_name ILIKE $1 || '%') DESC,
         similarity(name, $1) DESC, similarity(generic_name, $1) DESC
LIMIT $2
`

type SearchDrugsParams struct {
	Column1 pgtype.Text `json:"column_1"`
	Limit   int32       `json:"limit"`
}

// Prefix matches first (still GIN-trigram indexed), then typo-tolerant similarity.
// NOTE: $1 repeats; sqlc collapses it to a single Column1 (pgtype.Text) param.
func (q *Queries) SearchDrugs(ctx context.Context, arg SearchDrugsParams) ([]Drug, error) {
	rows, err := q.db.Query(ctx, searchDrugs, arg.Column1, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Drug
	for rows.Next() {
		var i Drug
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.GenericName,
			&i.NdcCode,
			&i.Strength,
			&i.Form,
			&i.Manufacturer,
			&i.CreatedAt,
			&i.RxOtc,
			&i.AtcCode,
			&i.TherapeuticCategory,
			&i.ShopperCategory,
			&i.NhisCovered,
			&i.GhanaEml,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchInventoryByDrug = `-- name: SearchInventoryByDrug :many
SELECT
    i.id, i.pharmacy_id, i.drug_id, i.quantity, i.price_cents, i.last_updated, i.source,
    p.name as pharmacy_name,
    p.address,
    p.city,
    p.state,
    p.zip_code,
    p.latitude,
    p.longitude,
    p.phone,
    p.hours,
    pc.name as chain_name,
    d.name as drug_name,
    d.generic_name,
    d.ndc_code,
    d.strength,
    d.form,
    earth_distance(ll_to_earth($1, $2), ll_to_earth(p.latitude, p.longitude)) as distance_meters
FROM inventory i
JOIN pharmacies p ON i.pharmacy_id = p.id
LEFT JOIN pharmacy_chains pc ON p.chain_id = pc.id
JOIN drugs d ON i.drug_id = d.id
WHERE i.drug_id = $3
  AND p.is_active = true
  AND i.quantity > 0
  AND earth_box(ll_to_earth($1, $2), $4) @> ll_to_earth(p.latitude, p.longitude)
ORDER BY distance_meters, i.price_cents ASC NULLS LAST
LIMIT $5
`

type SearchInventoryByDrugParams struct {
	LlToEarth   float64   `json:"ll_to_earth"`
	LlToEarth_2 float64   `json:"ll_to_earth_2"`
	DrugID      uuid.UUID `json:"drug_id"`
	EarthBox    float64   `json:"earth_box"`
	Limit       int32     `json:"limit"`
}

type SearchInventoryByDrugRow struct {
	ID             uuid.UUID       `json:"id"`
	PharmacyID     uuid.UUID       `json:"pharmacy_id"`
	DrugID         uuid.UUID       `json:"drug_id"`
	Quantity       int32           `json:"quantity"`
	PriceCents     pgtype.Int4     `json:"price_cents"`
	LastUpdated    time.Time       `json:"last_updated"`
	Source         InventorySource `json:"source"`
	PharmacyName   string          `json:"pharmacy_name"`
	Address        string          `json:"address"`
	City           string          `json:"city"`
	State          string          `json:"state"`
	ZipCode        string          `json:"zip_code"`
	Latitude       float64         `json:"latitude"`
	Longitude      float64         `json:"longitude"`
	Phone          pgtype.Text     `json:"phone"`
	Hours          []byte          `json:"hours"`
	ChainName      pgtype.Text     `json:"chain_name"`
	DrugName       string          `json:"drug_name"`
	GenericName    string          `json:"generic_name"`
	NdcCode        string          `json:"ndc_code"`
	Strength       pgtype.Text     `json:"strength"`
	Form           pgtype.Text     `json:"form"`
	DistanceMeters float64         `json:"distance_meters"`
}

func (q *Queries) SearchInventoryByDrug(ctx context.Context, arg SearchInventoryByDrugParams) ([]SearchInventoryByDrugRow, error) {
	rows, err := q.db.Query(ctx, searchInventoryByDrug,
		arg.LlToEarth,
		arg.LlToEarth_2,
		arg.DrugID,
		arg.EarthBox,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchInventoryByDrugRow
	for rows.Next() {
		var i SearchInventoryByDrugRow
		if err := rows.Scan(
			&i.ID,
			&i.PharmacyID,
			&i.DrugID,
			&i.Quantity,
			&i.PriceCents,
			&i.LastUpdated,
			&i.Source,
			&i.PharmacyName,
			&i.Address,
			&i.City,
			&i.State,
			&i.ZipCode,
			&i.Latitude,
			&i.Longitude,
			&i.Phone,
			&i.Hours,
			&i.ChainName,
			&i.DrugName,
			&i.GenericName,
			&i.NdcCode,
			&i.Strength,
			&i.Form,
			&i.DistanceMeters,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDrug = `-- name: UpdateDrug :one
UPDATE drugs
SET name = $2, generic_name = $3, ndc_code = $4, strength = $5, form = $6, manufacturer = $7
WHERE id = $1
RETURNING id, name, generic_name, ndc_code, strength, form, manufacturer, created_at, rx_otc, atc_code, therapeutic_category, shopper_category, nhis_covered, ghana_eml
`

type UpdateDrugParams struct {
	ID           uuid.UUID   `json:"id"`
	Name         string      `json:"name"`
	GenericName  string      `json:"generic_name"`
	NdcCode      string      `json:"ndc_code"`
	Strength     pgtype.Text `json:"strength"`
	Form         pgtype.Text `json:"form"`
	Manufacturer pgtype.Text `json:"manufacturer"`
}

func (q *Queries) UpdateDrug(ctx context.Context, arg UpdateDrugParams) (Drug, error) {
	row := q.db.QueryRow(ctx, updateDrug,
		arg.ID,
		arg.Name,
		arg.GenericName,
		arg.NdcCode,
		arg.Strength,
		arg.Form,
		arg.Manufacturer,
	)
	var i Drug
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.GenericName,
		&i.NdcCode,
		&i.Strength,
		&i.Form,
		&i.Manufacturer,
		&i.CreatedAt,
		&i.RxOtc,
		&i.AtcCode,
		&i.TherapeuticCategory,
		&i.ShopperCategory,
		&i.NhisCovered,
		&i.GhanaEml,
	)
	return i, err
}

const updatePharmacy = `-- name: UpdatePharmacy :one
UPDATE pharmacies
SET name = $2, address = $3, city = $4, state = $5, zip_code = $6,
    latitude = $7, longitude = $8, phone = $9, hours = $10, chain_id = $11,
    api_credentials_encrypted = $12, is_active = $13, updated_at = now()
WHERE id = $1
RETURNING id, name, address, city, state, zip_code, latitude, longitude, phone, hours, chain_id, api_credentials_encrypted, is_active, created_at, updated_at
`

type UpdatePharmacyParams struct {
	ID                      uuid.UUID   `json:"id"`
	Name                    string      `json:"name"`
	Address                 string      `json:"address"`
	City                    string      `json:"city"`
	State                   string      `json:"state"`
	ZipCode                 string      `json:"zip_code"`
	Latitude                float64     `json:"latitude"`
	Longitude               float64     `json:"longitude"`
	Phone                   pgtype.Text `json:"phone"`
	Hours                   []byte      `json:"hours"`
	ChainID                 pgtype.UUID `json:"chain_id"`
	ApiCredentialsEncrypted pgtype.Text `json:"api_credentials_encrypted"`
	IsActive                pgtype.Bool `json:"is_active"`
}

func (q *Queries) UpdatePharmacy(ctx context.Context, arg UpdatePharmacyParams) (Pharmacy, error) {
	row := q.db.QueryRow(ctx, updatePharmacy,
		arg.ID,
		arg.Name,
		arg.Address,
		arg.City,
		arg.State,
		arg.ZipCode,
		arg.Latitude,
		arg.Longitude,
		arg.Phone,
		arg.Hours,
		arg.ChainID,
		arg.ApiCredentialsEncrypted,
		arg.IsActive,
	)
	var i Pharmacy
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Address,
		&i.City,
		&i.State,
		&i.ZipCode,
		&i.Latitude,
		&i.Longitude,
		&i.Phone,
		&i.Hours,
		&i.ChainID,
		&i.ApiCredentialsEncrypted,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updatePharmacyAPIConfigSyncStatus = `-- name: UpdatePharmacyAPIConfigSyncStatus :exec
UPDATE pharmacy_api_configs
SET last_sync_at = $2, last_sync_status = $3
WHERE pharmacy_id = $1
`

type UpdatePharmacyAPIConfigSyncStatusParams struct {
	PharmacyID     uuid.UUID          `json:"pharmacy_id"`
	LastSyncAt     pgtype.Timestamptz `json:"last_sync_at"`
	LastSyncStatus NullSyncStatus     `json:"last_sync_status"`
}

func (q *Queries) UpdatePharmacyAPIConfigSyncStatus(ctx context.Context, arg UpdatePharmacyAPIConfigSyncStatusParams) error {
	_, err := q.db.Exec(ctx, updatePharmacyAPIConfigSyncStatus, arg.PharmacyID, arg.LastSyncAt, arg.LastSyncStatus)
	return err
}

const updatePharmacyChain = `-- name: UpdatePharmacyChain :one
UPDATE pharmacy_chains
SET name = $2, api_type = $3, base_endpoint = $4
WHERE id = $1
RETURNING id, name, api_type, base_endpoint, created_at
`

type UpdatePharmacyChainParams struct {
	ID           uuid.UUID   `json:"id"`
	Name         string      `json:"name"`
	ApiType      string      `json:"api_type"`
	BaseEndpoint pgtype.Text `json:"base_endpoint"`
}

func (q *Queries) UpdatePharmacyChain(ctx context.Context, arg UpdatePharmacyChainParams) (PharmacyChain, error) {
	row := q.db.QueryRow(ctx, updatePharmacyChain,
		arg.ID,
		arg.Name,
		arg.ApiType,
		arg.BaseEndpoint,
	)
	var i PharmacyChain
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ApiType,
		&i.BaseEndpoint,
		&i.CreatedAt,
	)
	return i, err
}

const updateRetryQueueAttempt = `-- name: UpdateRetryQueueAttempt :exec
UPDATE sync_retry_queue
SET attempt_count = attempt_count + 1,
    last_attempt_at = now(),
    next_retry_at = now() + ($2 * interval '1 second')
WHERE id = $1
`

type UpdateRetryQueueAttemptParams struct {
	ID      uuid.UUID   `json:"id"`
	Column2 interface{} `json:"column_2"`
}

func (q *Queries) UpdateRetryQueueAttempt(ctx context.Context, arg UpdateRetryQueueAttemptParams) error {
	_, err := q.db.Exec(ctx, updateRetryQueueAttempt, arg.ID, arg.Column2)
	return err
}

const updateUserFavorite = `-- name: UpdateUserFavorite :one
UPDATE user_favorites
SET notify_on_stock = $4
WHERE user_id = $1 AND drug_id = $2 AND pharmacy_id = $3
RETURNING id, user_id, drug_id, pharmacy_id, notify_on_stock, created_at
`

type UpdateUserFavoriteParams struct {
	UserID        uuid.UUID   `json:"user_id"`
	DrugID        uuid.UUID   `json:"drug_id"`
	PharmacyID    pgtype.UUID `json:"pharmacy_id"`
	NotifyOnStock pgtype.Bool `json:"notify_on_stock"`
}

func (q *Queries) UpdateUserFavorite(ctx context.Context, arg UpdateUserFavoriteParams) (UserFavorite, error) {
	row := q.db.QueryRow(ctx, updateUserFavorite,
		arg.UserID,
		arg.DrugID,
		arg.PharmacyID,
		arg.NotifyOnStock,
	)
	var i UserFavorite
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DrugID,
		&i.PharmacyID,
		&i.NotifyOnStock,
		&i.CreatedAt,
	)
	return i, err
}

const upsertGeocodeCache = `-- name: UpsertGeocodeCache :one
INSERT INTO geocode_cache (address_hash, address, latitude, longitude)
VALUES ($1, $2, $3, $4)
ON CONFLICT (address_hash) DO UPDATE SET
    latitude = EXCLUDED.latitude,
    longitude = EXCLUDED.longitude
RETURNING address_hash, address, latitude, longitude, created_at
`

type UpsertGeocodeCacheParams struct {
	AddressHash string  `json:"address_hash"`
	Address     string  `json:"address"`
	Latitude    float64 `json:"latitude"`
	Longitude   float64 `json:"longitude"`
}

func (q *Queries) UpsertGeocodeCache(ctx context.Context, arg UpsertGeocodeCacheParams) (GeocodeCache, error) {
	row := q.db.QueryRow(ctx, upsertGeocodeCache,
		arg.AddressHash,
		arg.Address,
		arg.Latitude,
		arg.Longitude,
	)
	var i GeocodeCache
	err := row.Scan(
		&i.AddressHash,
		&i.Address,
		&i.Latitude,
		&i.Longitude,
		&i.CreatedAt,
	)
	return i, err
}

const upsertInventory = `-- name: UpsertInventory :one
INSERT INTO inventory (pharmacy_id, drug_id, quantity, price_cents, last_updated, source)
VALUES ($1, $2, $3, $4, now(), $5)
ON CONFLICT (pharmacy_id, drug_id) DO UPDATE SET
    quantity = EXCLUDED.quantity,
    price_cents = EXCLUDED.price_cents,
    last_updated = now(),
    source = EXCLUDED.source
RETURNING id, pharmacy_id, drug_id, quantity, price_cents, last_updated, source
`

type UpsertInventoryParams struct {
	PharmacyID uuid.UUID       `json:"pharmacy_id"`
	DrugID     uuid.UUID       `json:"drug_id"`
	Quantity   int32           `json:"quantity"`
	PriceCents pgtype.Int4     `json:"price_cents"`
	Source     InventorySource `json:"source"`
}

func (q *Queries) UpsertInventory(ctx context.Context, arg UpsertInventoryParams) (Inventory, error) {
	row := q.db.QueryRow(ctx, upsertInventory,
		arg.PharmacyID,
		arg.DrugID,
		arg.Quantity,
		arg.PriceCents,
		arg.Source,
	)
	var i Inventory
	err := row.Scan(
		&i.ID,
		&i.PharmacyID,
		&i.DrugID,
		&i.Quantity,
		&i.PriceCents,
		&i.LastUpdated,
		&i.Source,
	)
	return i, err
}

const upsertPharmacyAPIConfig = `-- name: UpsertPharmacyAPIConfig :one
INSERT INTO pharmacy_api_configs (pharmacy_id, api_type, endpoint, credentials_ref, sync_schedule, is_enabled)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (pharmacy_id) DO UPDATE SET
    api_type = EXCLUDED.api_type,
    endpoint = EXCLUDED.endpoint,
    credentials_ref = EXCLUDED.credentials_ref,
    sync_schedule = EXCLUDED.sync_schedule,
    is_enabled = EXCLUDED.is_enabled
RETURNING id, pharmacy_id, api_type, endpoint, credentials_ref, sync_schedule, last_sync_at, last_sync_status, is_enabled
`

type UpsertPharmacyAPIConfigParams struct {
	PharmacyID     uuid.UUID   `json:"pharmacy_id"`
	ApiType        string      `json:"api_type"`
	Endpoint       pgtype.Text `json:"endpoint"`
	CredentialsRef pgtype.Text `json:"credentials_ref"`
	SyncSchedule   pgtype.Text `json:"sync_schedule"`
	IsEnabled      pgtype.Bool `json:"is_enabled"`
}

func (q *Queries) UpsertPharmacyAPIConfig(ctx context.Context, arg UpsertPharmacyAPIConfigParams) (PharmacyApiConfig, error) {
	row := q.db.QueryRow(ctx, upsertPharmacyAPIConfig,
		arg.PharmacyID,
		arg.ApiType,
		arg.Endpoint,
		arg.CredentialsRef,
		arg.SyncSchedule,
		arg.IsEnabled,
	)
	var i PharmacyApiConfig
	err := row.Scan(
		&i.ID,
		&i.PharmacyID,
		&i.ApiType,
		&i.Endpoint,
		&i.CredentialsRef,
		&i.SyncSchedule,
		&i.LastSyncAt,
		&i.LastSyncStatus,
		&i.IsEnabled,
	)
	return i, err
}
