// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	AddToRetryQueue(ctx context.Context, arg AddToRetryQueueParams) (SyncRetryQueue, error)
	BulkUpsertInventory(ctx context.Context, arg BulkUpsertInventoryParams) error
	CreateDrug(ctx context.Context, arg CreateDrugParams) (Drug, error)
	CreatePharmacy(ctx context.Context, arg CreatePharmacyParams) (Pharmacy, error)
	CreatePharmacyChain(ctx context.Context, arg CreatePharmacyChainParams) (PharmacyChain, error)
	CreateUserFavorite(ctx context.Context, arg CreateUserFavoriteParams) (UserFavorite, error)
	DeleteDrug(ctx context.Context, id uuid.UUID) error
	DeletePharmacy(ctx context.Context, id uuid.UUID) error
	DeletePharmacyChain(ctx context.Context, id uuid.UUID) error
	DeleteRetryQueueItem(ctx context.Context, id uuid.UUID) error
	DeleteUserFavorite(ctx context.Context, arg DeleteUserFavoriteParams) error
	GetDrugByID(ctx context.Context, id uuid.UUID) (Drug, error)
	GetDrugByNDC(ctx context.Context, ndcCode string) (Drug, error)
	GetDueRetryQueue(ctx context.Context, limit int32) ([]SyncRetryQueue, error)
	GetEnabledPharmacyAPIConfigs(ctx context.Context) ([]GetEnabledPharmacyAPIConfigsRow, error)
	GetGeocodeCache(ctx context.Context, addressHash string) (GeocodeCache, error)
	GetInventoryByPharmacyAndDrug(ctx context.Context, arg GetInventoryByPharmacyAndDrugParams) (GetInventoryByPharmacyAndDrugRow, error)
	GetPharmaciesNearby(ctx context.Context, arg GetPharmaciesNearbyParams) ([]GetPharmaciesNearbyRow, error)
	GetPharmacyAPIConfig(ctx context.Context, pharmacyID uuid.UUID) (PharmacyApiConfig, error)
	GetPharmacyByID(ctx context.Context, id uuid.UUID) (GetPharmacyByIDRow, error)
	GetPharmacyChainByID(ctx context.Context, id uuid.UUID) (PharmacyChain, error)
	GetPharmacyChains(ctx context.Context) ([]PharmacyChain, error)
	GetPharmacyInventory(ctx context.Context, arg GetPharmacyInventoryParams) ([]GetPharmacyInventoryRow, error)
	GetUserFavorites(ctx context.Context, userID uuid.UUID) ([]GetUserFavoritesRow, error)
	// Prefix matches first (still GIN-trigram indexed), then typo-tolerant similarity.
	// NOTE: $1 repeats; sqlc collapses it to a single Column1 (pgtype.Text) param.
	SearchDrugs(ctx context.Context, arg SearchDrugsParams) ([]Drug, error)
	SearchInventoryByDrug(ctx context.Context, arg SearchInventoryByDrugParams) ([]SearchInventoryByDrugRow, error)
	UpdateDrug(ctx context.Context, arg UpdateDrugParams) (Drug, error)
	UpdatePharmacy(ctx context.Context, arg UpdatePharmacyParams) (Pharmacy, error)
	UpdatePharmacyAPIConfigSyncStatus(ctx context.Context, arg UpdatePharmacyAPIConfigSyncStatusParams) error
	UpdatePharmacyChain(ctx context.Context, arg UpdatePharmacyChainParams) (PharmacyChain, error)
	UpdateRetryQueueAttempt(ctx context.Context, arg UpdateRetryQueueAttemptParams) error
	UpdateUserFavorite(ctx context.Context, arg UpdateUserFavoriteParams) (UserFavorite, error)
	UpsertGeocodeCache(ctx context.Context, arg UpsertGeocodeCacheParams) (GeocodeCache, error)
	UpsertInventory(ctx context.Context, arg UpsertInventoryParams) (Inventory, error)
	UpsertPharmacyAPIConfig(ctx context.Context, arg UpsertPharmacyAPIConfigParams) (PharmacyApiConfig, error)
}

var _ Querier = (*Queries)(nil)
